# Generated by Django 5.2 on 2025-07-06 20:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0003_alter_run_athlete'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='athlete_info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('goals', models.TextField(default='')),
                ('weight', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(900.0)])),
            ],
            options={
                'verbose_name': 'Athlete Info',
                'verbose_name_plural': 'Athlete Info',
            },
        ),
    ]
