# Generated by Django 5.2 on 2025-07-20 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0017_alter_run_speed_alter_subscription_athlete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
